blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    # path('blog/', views.blog, name='blog')
    path('blog/', views.ArticlesListView.as_view(), name='blog')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

credit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('blog.urls')),
    path('', include('article.urls')),
    path('', include('accounts.urls')),
    path('silk/', include('silk.urls', namespace='silk')),
]   

article/models.py
from email.policy import default
from unicodedata import name
from django.db import models
from django.urls import reverse

# Create your models here.
class Article(models.Model):
    
    title = models.CharField('Название', max_length=100)
    slug = models.SlugField('Ссылка', blank=True, null=True, unique=True, db_index=True)
    text = models.TextField('Текст')
    date = models.DateField('Дата', auto_now_add=True)
    description = models.CharField('Описание', max_length=250)
    article_image = models.ImageField('Изборажение', null=True, upload_to='article/')
    big_status = models.BooleanField('Большая статья', default=False)
    preview_image = models.ImageField('Предварительное изображение', upload_to='article/')
    
    
    def __str__(self):
        return self.title
    
    
    def get_absolute_url(self):
        return reverse("article", kwargs={"slug": self.slug})
    

    
    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['date', 'title']

templates/includes/footer.html
{% load static %}

<footer class="footer">
    <span class="footer__text">
        Представленная на сайте информация может являться не полной и носит ознакомительный характер. Полные условия финансовых услуг и все непосредственные решения принимаются исключительно банками и МФО, предоставляющими свои услуги. Администрация сайта не несёт ответственности за достоверность условий и финансовые услуги не оказывает. 
    </span>
</footer>

templates/includes/header.html
{% load static %}

<header class="header">
    <div class="header__content menu">
        <div class="menu__icon">
            <span></span>
        </div>
        <img src="{% static 'main/img/icons/logo.svg'%}" alt="" class="header__logo">
        <nav class="header__nav">
            <ul class="header__list">
                <li class="list__item">
                    <a href="{% url 'main' %}" class="list__link">Главная </a>
                </li>
                <li class="list__item">
                    <a href="{% url 'blog' %}" class="list__link">Блог</a>
                </li>
                <li class="list__item">
                    <a href="#best-service__title" class="list__link burger-scroll-item">Займы онлайн</a>
                </li>
                <li class="list__item">
                    <a href="#news" class="list__link burger-scroll-item">Новости</a>
                </li>
            </ul>
        </nav>
        <div class="header__socials">
            <a href="https://vk.com/potom_verny" class="socials__links social-vk" target="_blank">
                <img src="{% static 'main/img/icons/socials_vk.svg' %}" alt="">
            </a>
            <!-- <div class="socials__links social-vk"><a href=""></a></div> -->
            <a href="https://dzen.ru/potomverny" class="socials__links social-wtup" target="_blank">
                <img src="{% static 'main/img/icons/socials_wup.svg' %}" alt="">
            </a>
            <a href="https://t.me/potomverny" class="socials__links social-teleg" target="_blank">
                <img src="{% static 'main/img/icons/socials_teleg.svg' %}" alt="">
            </a>
        </div>
    </div>
</header>

templates/includes/news.html
{% load static %}

<div class="content__news-block" id="news">
    <h2>Новости</h2>
    <div class="news-block__card-wrap">
        <div class="news-block__news-cards">
            {% if news|length > 0  %}
            {% for item in news %}
            <div class="news-block__card">
                <img src="{{ item.image.url }}" alt="" class="news-block__card__img">
                <div class="news-block__card__text">
                    <span>{{ item.text }}</span>
                </div>
            </div>
            {% endfor %}
            {% endif  %}
        </div>
    </div>
</div>

templates/includes/service.html
{% load static %}

{% if services|length > 0 %}
    {% for service in services %}
        {% if service.display == True %}
            <div class="service">
                <img src="{{service.image.url}}" alt="">
                <div class="service__bottom">
                    <p class="service__limit">До <span class="service__limit__price">{{service.money_limit}}</span> рублей</p>
                    <p class="service__percent">{{ service.text_left_from_stake }} <span class="service__limit__price">{{service.stake}}</span>% {{ service.text_right_from_stake }}</p>
                    <p class="service__age">Возраст от <span class="service__age__amount">{{service.age_start}}-{{service.age_end}}</span> лет</p>
                    <p class="service__more-info">
                        <a href="#">
                            Подробнее
                        </a>
                        <div class="service__more-info__block">
                            <span>
                                {{service.more_info}}
                            </span>
                        </div>
                    </p>
                    <a class="service__button" href="{{ service.url }}">Получить</a>
                </div>
            </div>
        {% endif %}
    {% endfor %}

    {% for service in services_second %}
        {% if service.display == True %}
            <div class="service services_second">
                <img src="{{service.image.url}}" alt="">
                <div class="service__bottom">
                    <p class="service__limit">До <span class="service__limit__price">{{service.money_limit}}</span> рублей</p>
                    <p class="service__percent">{{ service.text_left_from_stake }} <span class="service__limit__price">{{service.stake}}</span>% {{ service.text_right_from_stake }}</p>
                    <p class="service__age">Возраст от <span class="service__age__amount">{{service.age_start}}-{{service.age_end}}</span> лет</p>
                    <p class="service__more-info">
                        <a href="#">
                            Подробнее
                        </a>
                        <div class="service__more-info__block">
                            <span>
                                {{service.more_info}}
                            </span>
                        </div>
                    </p>
                    <a class="service__button" href="{{ service.url }}">Получить</a>
                </div>
            </div>
        {% endif %}
    {% endfor %}
{% endif  %}

templates/includes/service_form.html
<div class="questions-wrap">
    <div class="questions-block">
        
        <form id="sort_loans" action="/service_find/" method="POST" class="questions-form">
            {% csrf_token %}

            <div class="form__close_button">
                <span></span>
            </div>

            <h3>Опросы</h3>

            <div class="questions-form__questions">
                <fieldset class="question-1">
                    <legend>Укажите ваш возраст</legend>
                    {{ form.age }}
                </fieldset>

                <fieldset class="question-2">
                    <legend for="sum">Укажите сумму займа</legend>
                    {{ form.sum }}
                </fieldset>

                <fieldset class="question-3">
                    <legend>На какой срок вы хотите взять займ</legend>
                    {{ form.duration}}
                </fieldset>

                <fieldset class="question-4">
                    <legend>Есть ли у вас непогашенный кредит/займ</legend>
                    {{ form.is_autstanding}}
                </fieldset>

                <fieldset class="question-5">
                    <legend>Вы хотите получить деньги в руки или на карту</legend>
                    {{ form.how_get}}
                </fieldset>
             </div>
            <button form="sort_loans" class="questions-form__button">Применить</button>

        </form>
    </div>
</div>

templates/includes/small_articles.html
{% load static %}

<div class="small-articles-wrap">
    {% for article in object_list.article_list %}
    <div class="article small-article">
        <img src="{{ article.preview_image.url }}" alt="" class="big-article__img"> <!-- img/blog/small_article_1.jpg -->
        <p class="article__title">{{article.title}}</p>
        <p class="article__text">{{article.description}}</p>
        <div class="article__bottom-block">
            <div class="article__button"><a href="{{ article.get_absolute_url }}">Подробнее</a></div>
            <div class="article__date">
              <span>{{article.date}}</span>
            </div>
        </div>
    </div>
    {% endfor %}
</div>